### ISSUE TITLE
Exporting environment variable ORCHESTRATE_API_KEY

### ISSUE THREAD

**Issue by tremendus** [chadtmiller/ember-orchestrate-adapter#10]
Chad, thanks for your work on this. 

One question: 

> You will also need to set en environment variable with an api key provided from the Orchestrate.io dashboard.
> 
> export ORCHESTRATE_API_KEY=...

So what's the right way to do this with ember-cli? I searched around, there is some discussion on this by setting and importing config from '../config/environment' etc but seems hoakey, some are using node modules (Nodejs Dotenv project), but is that really necessary? I'm new to ember-cli but I'd like to say with the ember 'doctrine' if you have a method you would share.

**Comment by bigmoves** [comment]
@tremendus You should treat the Orchestrate api key like would any other environment variable in a server-side environment. Anything you put into the `config/environment.js` file is exposed in the index.html file even if you refer to an environment variable with node's `process.env`, so I would not recommend storing it there. In development, Ember-cli is served by an express server so you can just export the api key on your path, as I mentioned in the README, and the proxy server at `server/proxies/orchestrate.js` will pick it up. In a production environment, you'll need to create a separate server environment in order to proxy requests to Orchestrate (I would not recommend using `ember server` for this). 

I hope this isn't too confusing. It would be great if we could store the key client-side, but at the moment Orchestrate doesn't provide user authentication utilities like Firebase or Parse, so your database would be completely exposed. Instead, you need to proxy requests from a separate server and roll your own authentication. I'm working on an example I can share with a way to do this, but for now you check out the [parks-and-rec](https://github.com/chadtmiller/parks-and-rec) app I made with `ember-orchestrate`. Specifically, check out the `index.js` file to see how you can make a simple proxy server. In this case, I am running the proxy server on heroku and all of the assets are hosted by divshot.

Let me know if you have any other questions :smile:

**Comment by tremendus** [comment]
Understood. I hadn’t realized orchestrate doesn’t handle client requests. 

I’ll check out that index.js, but I know nodejitsu has an tight little proxy too, haven’t worked with it though. 

Darren CarterTremendus Apps Inc
darren@tremendusapps.com

403.618.5338
